### ISSUE TITLE
Imported Products Not Linked to Categories

### ISSUE THREAD

**Issue by shaabans** [synolia/Prestaneo#4]
Thanks for this module, it's working well in importing Akeneo data (I previously opened and then closed my own ticket, finding that the problem was mine, not the module's).

But I'm seeing what looks like a real issue now:  Importing categories works well and maps Akeneo category codes to PS category IDs. However, importing products does not seem to map them to their corresponding categories in PS.

Could you test this functionality on your end to determine if it's really a bug?  And if so, could you provide advice on where to troubleshoot?

**Comment by Rmnndr** [comment]
Hi Sam, 

Thanks for your feedback.
We know that what you mentionned is not a real issue and that the association between products and categories works.

Could you please check the mapping fields you have to set up in the config panel ?
You must provide the column name you find in the Akeneo CSV export to make a link between this information and what PrestaShop expected.

![image](https://cloud.githubusercontent.com/assets/14890595/20107283/3b697994-a5d8-11e6-86b3-dbef74cdc6ca.png)

**Comment by shaabans** [comment]
Thank you for the quick reply!  Our categories mappings is exactly as you have shown, and I see the correct category mappings in the ps_mapping_code_categories table.

A sample from our Akeneo product export looks like the following:

sku;categories;enabled;name-en_US
1234;103,105,114,125;1;"Sample Name"

Can you advise me on anything else I should check?

**Comment by shaabans** [comment]
Ah ha, thank you again for your original advice, I did notice a misspelling in the mapping name within the config screen you showed!

Again, thank you!!
