### ISSUE TITLE
Does not work with prestashop 1.7

### ISSUE THREAD

**Issue by chrisseven** [synolia/Prestaneo#5]
Sadly it seems that this modul is not ready for prestashop 1.7.

**Comment by synoxzi** [comment]
Hello, unfortunately no. We will work on a specific Prestashop 1.7 module version, but nowadays it is still in project. Thank you for pointing that out, and we hope to release a compatible version soon.

**Comment by lmartinpulse** [comment]
Hi,
Just a little message to beg you to make it ready for Prestashop 1.7!
:-)

**Comment by Rmnndr** [comment]
Hi everyone, 

Prestashop 1.7 support is effectively not included in our roadmap for this addon yet.
Feel free to help us to make Akeneo and Prestashop great together by conributing your code on it!

**Comment by wucherpfennig** [comment]
Dear @Rmnndr 

I contacted you several times via your contact form on your website (synolia) but it looks like you are not interested to work with us?

best regards

wucherpfennig

**Comment by Rmnndr** [comment]
Hi @wucherpfennig,

I'm unfortunatly not behind the diffusion list of the general contact form of our a website.
Sorry for the lack of answer, I'll shed the light on this. 

Even if the support of Prestashop 1.7 is still not in our roadmap, it's in our global discussions around Akeneo 2.0 support. We will appreciate the help of each contributor.

Please, feel free to send me a new message through our Akeneo dedicated website: http://akeneo.synolia.com. I'll take care of it.

Best regards,

**Comment by wucherpfennig** [comment]
Dear @Rmnndr 

How do you mean: " it's in our global discussions around Akeneo 2.0 support."?

**Comment by Rmnndr** [comment]
Dear @wucherpfennig

We're currently building our roadmap around all our the potential actions about Akeneo, in general.
I mean about Akeneo ad its new version, and all the addons we developp.

Our current main concerns are around the Akeneo 2.0 compatibility (some standard csv export have been modified in this new version) but we have also to study how we can make Prestaneo compatible with th1.7 of PrestaShop.

I finally find your initial email. I will study what we can do together before to plan a deeper call / you.
Keep you posted,

Best,

**Comment by wucherpfennig** [comment]
Dear @Rmnndr 

considering that the "new" UI does not allow you to create variants yet version 2.0 does not appear to be "production ready".

anyway please feel free to contact me about your future roadmap. my best guess to achieve compability would be to use the prestashop API and a proper akeneo plugin...
