### ISSUE TITLE
Update Stock not possible

### ISSUE THREAD

**Issue by wucherpfennig** [synolia/Prestaneo#7]
How do you update product stock?

**Comment by Rmnndr** [comment]
Hi Wucherpfennig,

Thanks for your feedback.
The product stock is considered as a "hot data" you must manage outside of a PIM as Akeneo.

We don't plan to manage the stock information via the public version of this extension.
It's maybe possible by playing with the attributes mapping offered in the setup panel of the out of the box addon. This notion has always been outside of our test scope.

Regards,

**Comment by wucherpfennig** [comment]
Sorry for the late reply but the project was on hold.

We know about the "hot data" but since the sync (as far for stock) erp > pim > shop there is no problem.
